title: DS Blog
description: descrição do meu blog

url: https://diegofds.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contact

social:
   github: diegofds
   twitter: 
   facebook: https://www.facebook.com/diego.faria.jpa
   email: ti.diegof@gmail.com

google_analytics: 
